//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalExamen.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Visita
    {
        public int ID { get; set; }
        public string Motivo_Visita { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Fecha_Visita { get; set; }
        [DataType(DataType.Time)]
        public Nullable<System.DateTime> Hora_Entrada { get; set; }
        [DataType(DataType.Time)]
        public Nullable<System.DateTime> Hora_Salida { get; set; }
        public string Nombre_Completo { get; set; }
        public string Contacto_Recibio { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
